services:
    - type: web
      name: yuta
      runtime: docker
      plan: free
      dockerfilePath: ./Dockerfile
      envVars:
          - key: APP_KEY
            generateValue: true
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: LOG_CHANNEL
            value: stderr
          - key: APP_URL
            sync: false
          - key: FILESYSTEM_DISK
            value: r2
          - key: R2_ACCESS_KEY_ID
            sync: false
          - key: R2_SECRET_ACCESS_KEY
            sync: false
          - key: R2_BUCKET
            sync: false
          - key: R2_ENDPOINT
            sync: false
          - key: DB_CONNECTION
            value: pgsql
          - key: DB_HOST
            sync: false
          - key: DB_PORT
            value: 5432
          - key: DB_DATABASE
            sync: false
          - key: DB_USERNAME
            sync: false
          - key: DB_PASSWORD
            sync: false
